config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root 'topics#index'
  resources :tags
  resources :topics do
    resources :posts do
      member do
        post 'mark_as_read'
      end
      resources :ratings
      resources :comments
    end
  end
  get '/posts', to: 'posts#index'
  resources :user_comment_ratings, only: [:new, :create]
  get 'view_ratings', to: 'user_comment_ratings#view_ratings'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post , counter_cache: true
  validates :content,length: {minimum: 4}
  belongs_to :user
  has_many :user_comment_ratings
  has_many :users, through: :user_comment_ratings
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :set_comment, only: %i[show edit update destroy]
  load_and_authorize_resource
  # GET /comments or /comments.json
  def index
    @comments = @post.comments.eager_load(:user).all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = @post.comments.new
  end

  # GET /comments/1/edit
  def edit
    #authorize! :edit,@comment
  end

  # POST /comments or /comments.json
  def create
    @comment = @post.comments.new(comment_params)
    @comment.user=current_user
    respond_to do |format|
      if @comment.save
        format.html { redirect_to topic_post_comments_path(@post.topic,@post), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    #authorize! :update,@comment
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to topic_post_comments_path(@post.topic,@post), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    #authorize! :destroy,@comment
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to topic_post_comments_path(@post.topic,@post), notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end
  def set_post
    @post=Post.find(params[:post_id])
  end
    # Only allow a list of trusted parameters through.
  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div , class="box">
  <p>
    <% if (comment.user.present?) %>
    <strong>Author Mail : </strong>
    <%=comment.user.email %><br>
      <%end %>
    <strong>Content:</strong>
    <%#=  comment.content %>
    <%= link_to comment.content, view_ratings_path(comment_id: comment.id),class: "link" %>

  </p>
</div>

app/views/comments/_form.html.erb
<div class="box">
<%= form_with(model: [ @post.topic, @post, @comment]) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment",topic_post_comment_path(@post.topic,@post,@comment),class: "link" %> |
  <%= link_to "Back to comments", topic_post_comments_path(@post.topic,@post),class: "link" %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%if can?(:manage,comment) %>
      <%= link_to "Show this comment",topic_post_comment_path(@post.topic,@post,comment),class:"link"%>
      <%end %>
        </p>
    <%= render 'user_comment_ratings/form', comment: comment %>
    <%#= link_to 'View Ratings', view_ratings_path(comment_id: comment.id),class: "link" %>
    <% end %>
</div>

<%= link_to "New comment", new_topic_post_comment_path,class:"link" %>
<%= link_to "Back to Post",topic_posts_path,class:"link" %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", topic_post_comments_path(@post.topic,@post),class:"link" %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_topic_post_comment_path(@post.topic,@post,@comment),class:"link" %> |
  <%= link_to "Back to comments",  topic_post_comments_path(@post.topic,@post),class:"link"%>

  <%= button_to "Destroy this comment",topic_post_comment_path(@post.topic,@post,@comment), method: :delete,class:"button" %>
</div>