config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root 'topics#index'
  resources :tags
  resources :topics do
    resources :posts do
      member do
        post 'mark_as_read'
      end
      resources :ratings
      resources :comments
    end
  end
  get '/posts', to: 'posts#index'
  resources :user_comment_ratings, only: [:new, :create]
  get 'view_ratings', to: 'user_comment_ratings#view_ratings'
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :title,:content ,length: { minimum: 5 }
  has_many :posts, dependent: :destroy
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: %i[ show edit update destroy ]

  # GET /topics or /topics.json
  def index
    @topics = Topic.all

  end

  # GET /topics/1 or /topics/1.json
  def show

  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics or /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topic_url(@topic), notice: "Topic was successfully created." }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1 or /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to topic_url(@topic), notice: "Topic was successfully updated." }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1 or /topics/1.json
  def destroy
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to topics_url, notice: "Topic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def topic_params
      params.require(:topic).permit(:title, :content)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_with(model: topic) do |form| %>
  <% if topic.errors.any? %>

    <div class="alert alert-danger" role="alert">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
        <% topic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class= "mb-3">
    <%= form.label :title, style: "display: block" ,class: "form-label"%>
    <%= form.text_field :title,class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :content, style: "display: block",class: "form-label" %>
    <%= form.text_area :content,class: "form-control" %>
  </div>
<!--  <button type= "submit" class="btn btn-primary">Submit</button>-->
  <div >
    <%= form.submit "Submit",class: "btn btn-primary"%>
  </div>
<% end %>
<!--<form>-->
<!--  <div class="mb-3">-->
<!--    <label for="exampleInputEmail1" class="form-label">Email address</label>-->
<!--    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">-->
<!--    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>-->
<!--  </div>-->
<!--  <div class="mb-3">-->
<!--    <label for="exampleInputPassword1" class="form-label">Password</label>-->
<!--    <input type="password" class="form-control" id="exampleInputPassword1">-->
<!--  </div>-->
<!--  <div class="mb-3 form-check">-->
<!--    <input type="checkbox" class="form-check-input" id="exampleCheck1">-->
<!--    <label class="form-check-label" for="exampleCheck1">Check me out</label>-->
<!--  </div>-->
<!--  <button type="submit" class="btn btn-primary">Submit</button>-->
<!--</form>-->

app/views/topics/_topic.html.erb
 <div class="box">
  <strong>Title:  </strong>
    <%= topic.title %>
    <br>
    <strong>Content:  </strong>
    <%= topic.content %>
   <br>
</div>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render "form", topic: @topic %>

<br>

<div>
  <%= link_to "Show this topic", @topic,class: "link" %> <br>
  <%= link_to "Back to topics", topics_path,class: "link" %><br>
</div>

app/views/topics/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Topics</h1>

<div >
  <% @topics.each do |topic| %>
      <%= render topic %>

      <%= link_to "Show this topic", topic ,class: "btn btn-primary"%><br><br>
      <%= link_to "Show Posts",topic_posts_path(topic),class: "link" %>
    <br>
  <% end %>

</div>
<br>
<%= link_to "New topic", new_topic_path,class: "link" %>

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= render "form", topic: @topic %>

<br>

<div>
  <%= link_to "Back to topics", topics_path,class: "link" %>
</div>

app/views/topics/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @topic %>

<div>
  <%= link_to "Edit this topic", edit_topic_path(@topic) ,class: "link"%>
  <%= link_to "Back to topics", topics_path ,class: "link"%>
<br><br>
  <%= button_to "Destroy this topic", @topic, method: :delete,class: "button" %>
</div>