config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root 'topics#index'
  resources :tags
  resources :topics do
    resources :posts do
      member do
        post 'mark_as_read'
      end
      resources :ratings
      resources :comments
    end
  end
  get '/posts', to: 'posts#index'
  resources :user_comment_ratings, only: [:new, :create]
  get 'view_ratings', to: 'user_comment_ratings#view_ratings'
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  belongs_to :topic
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :tags
  has_many :ratings, dependent: :destroy
  has_one_attached :image
  has_and_belongs_to_many :read_by_users, class_name: 'User', join_table: :posts_users_read_statuses

  belongs_to :user

  scope :filter_by_date,->(start_date,to_date){ (where "Date(posts.created_at) >=? and Date(posts.created_at)<=?",start_date,to_date) }
  # def average_rating
  #   return 0 if ratings.empty?
  #   ratings.average(:star).truncate(1)
  # end
   # def comment_count
   #    return 0 if comments.empty?
   #    comments.count
   # end
  def update_rating_average
    new_average = ratings.average(:star)
    update_column(:rating_average, new_average)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_topic
  before_action :set_post, only: %i[show edit update destroy]
  load_and_authorize_resource
  # GET /topics/:topic_id/posts or /topics/:topic_id/posts.json
  def index
    if params[:topic_id].present?
      @posts = @topic.posts.eager_load(:user, :tags, :ratings, :comments).page(params[:page]).per(3)
    else
      if params[:post].present?
        @start_date = params[:post][:start_date].present? ? Date.parse(params[:post][:start_date].to_s) : Date.yesterday
        @to_date = params[:post][:to_date].present? ? Date.parse(params[:post][:to_date].to_s) : Date.today
      else

        @start_date = Date.yesterday
        @to_date = Date.today
      end
      #puts @start_date,@to_date
      @posts = Post.filter_by_date(@start_date,@to_date).eager_load(:topic,:user, :tags, :ratings, :comments).page(params[:page]).per(3)

    end

  end

  # GET /posts/1 or /posts/1.json
  def show

    @rating = Rating.new
    @star_counts = @post.ratings.group(:star).count

  end

  # GET /topics/:topic_id/posts/new
  def new

    @post = @topic.posts.new
     respond_to  do |format|
       format.js
       format.html {render :new}
     end
  end

  # GET /posts/1/edit
  def edit
    #authorize! :edit, @post
  end

  # POST /topics/:topic_id/posts or /topics/:topic_id/posts.json
  def create
    @post = @topic.posts.new(post_params)
    @post.user=current_user
    if params[:post][:tag_ids].present?
      @post.tags = Tag.where(id: params[:post][:tag_ids])
    end

    if params[:post][:tag_names].present?
      new_tags = params[:post][:tag_names].split(',').map(&:strip)
      new_tags.each { |tag_name| @post.tags << Tag.find_or_create_by(name: tag_name) }
    end
    puts request.format
    respond_to do |format|
    if @post.save

          format.js
          format.html { redirect_to topic_post_path(@topic, @post), notice: "Post was successfully created." }

          format.json { render :show, status: :created, location: @post }


    else
        format.js
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
    Rails.logger.info "Requested Format: #{request.format}"
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    #authorize! :update, @post
    @post.tags = Tag.where(id: params[:post][:tag_ids])
     if params[:post][:tag_ids].present?
       @post.tags = Tag.where(id: params[:post][:tag_ids])
     end

     if params[:post][:tag_names].present?
       new_tags = params[:post][:tag_names].split(',').map(&:strip)
       new_tags.each { |tag_name| @post.tags << Tag.find_or_create_by(name: tag_name) }
     end

    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to topic_post_path(@topic, @post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    #authorize! :destroy,@post
    @post.destroy

    respond_to do |format|
      format.html { redirect_to topic_posts_url(@topic), notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  def mark_as_read
    #if current_user.read_posts.exclude?(@post)
      current_user.read_posts << @post
    # end
    head :no_content

  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = @topic.posts.find(params[:id])

  end

  def find_topic
    if (params[:topic_id].present?)
      @topic = Topic.find(params[:topic_id])
    end
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :content,:image, tags_attributes:  [:id, :name] )
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div id="form-container">
<%=form_with(model: [@topic,@post], data: {remote: true},format: :js ,id: "new-post") do |form| %>
<%#= form_with(model: [@topic, @post], remote: true,format: :js, id:"new-post" ) do |form| %>

  <% if @post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% @post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>
  <div>
    <%=form.label :tag_attributes, 'Tags' %><br>
    <% Tag.all.each do |tag| %>

      <%= form.check_box :tag_ids,{multiple: true}, tag.id,nil %>
      <%= form.label tag.name %>
      <br>
    <% end %>
  </div>
  <div>
    <%= form.fields_for :tags_names, Tag.new do |tag_form| %>
      <%= tag_form.label :name, 'New Tag' %>
      <%= tag_form.text_field :name %>
    <% end %>
  </div>
  <div>
    <%= form.file_field :image %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/posts/_post.html.erb
<% if (post.user.present?) %>
 <strong>Author Mail : </strong>
 <%=post.user.email %><br>
   <%end%>
 <strong>Title:</strong>
    <%= post.title%>
  <%= "(#{post.topic.title})" %>
<br>
    <strong>Content:</strong>
    <%= post.content %>
  <br>
    <strong>Tags: </strong>

    <% post.tags.each do|t| %>
    <%= t.name  %>
     <%end %><br>
 <strong>Average Rating: </strong>
 <%= post.rating_average %><br>
 <strong> Comments Count: </strong>
 <%= post.comments_count %><br>
<strong>Rating count: </strong>
<%=post.ratings_count %><br>

app/views/posts/create.js.erb
// Display the loading image

<% if @post.errors.any? %>

       alert( "<%= j @post.errors.full_messages.join ", " %>" );
       window.location.href="<%=new_topic_post_url(@post.topic,@post) %>"

<% else %>

alert('Post was successfully created.');

    window.location.href = "<%= topic_post_path(@post.topic, @post) %>";

<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post",topic_post_path(@post.topic, @post) ,class: "link"%> |
  <%= link_to "Back to posts", topic_posts_path ,class: "link"%>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>
<div >
  <% if params[:topic_id].present? %>
      <p>
      <% @posts.each do |post| %>
          <div class="box">
            <%= render post %>
            <strong>Status: </strong>
            <%= 'unread' if current_user.read_posts.exclude?(post) %>
            <%=  'Read' if current_user.read_posts.include?(post)%>
          </div>

      <br>
      <%= link_to "Comments",topic_post_comments_path(post.topic,post),class: "link" %>
      <br><br>

          <%= link_to "Show this post", topic_post_path(post.topic, post) ,class: "link" %>

      <% end %>
      </p>

    <div id="new-post-form-container">
      <%=link_to "new post",new_topic_post_path,class:"link",remote: true %>
    </div>

    <%#= turbo_frame_tag "new_post_form" do%>
    <%#= link_to "New post", new_topic_post_path ,class: "link"%>
    <%#end %>
     <%= link_to "Back to Topics",topics_path ,class: "link"%> <br><br>
    <%= link_to_previous_page @posts, '<<Previous page ' ,class: "link" %>
    <%= link_to_next_page @posts, ' Next page>>',class: "right"%>
  <%else %>
    <%#= form_tag posts_path ,method: :get do %>
<!--      <%#=date_field 'start_date',params[:start_date] %><br>-->
      <%#= date_field 'to_date',params[:to_date] %>
      <%#=submit_tag 'find' %>
    <%# end %>
    <%=form_with(model: Post.new,url:posts_path,method: :get) do |f|%>
      <%=f.date_field :start_date %><br>
      <%= f.date_field :to_date %>
      <%=f.submit 'find' %>
      <%end %>

   <% @posts.each do |post| %>
          <%= render post %><br>
          <%= link_to "Show this post", topic_post_path(post.topic, post) ,class: "link" %>
        <%end %>
      <br><br>
    <%#= paginate @posts, params: { start_date: @start_date, to_date: @to_date }  %>
      <%= link_to_previous_page @posts, '<< Previous page ', params: {post: { start_date: @start_date, to_date: @to_date } },class: "link" %>
      <%= link_to_next_page @posts, ' Next page >>', params: { post: { start_date: @start_date, to_date: @to_date } },class: "right"  %>
    <% end %>



</div>
<script>
    // Show loading overlay when the page starts loading
    window.addEventListener('beforeunload', function() {
        document.getElementById('custom-loading-overlay').style.display = 'block';
    });

    // Hide loading overlay when the page is fully loaded
    window.addEventListener('load', function() {
        document.getElementById('custom-loading-overlay').style.display = 'none';
    });
</script>

app/views/posts/new.html.erb
<h1>New post</h1>
<%#= turbo_frame_tag "new_post_form" do%>
  <%= render 'form' %>
<%#end %>

<br>

<div>
  <%= link_to "Back to posts",topic_posts_path,class: "link" %>
</div>

app/views/posts/new.js.erb
document.getElementById('new-post-form-container').innerHTML = '<%= j render("form", post: @post) %>';

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>
<% unless current_user.read_posts.pluck(:id).include?(@post.id) %>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script>
      $(document).ready(function() {
          $.ajax({
              url: '<%= mark_as_read_topic_post_path(@post.topic, @post) %>',
              type: 'POST',
              beforeSend: function(xhr) {
                  xhr.setRequestHeader('X-CSRF-Token', '<%= form_authenticity_token %>');
              },
              success: function(response) {
                  console.log('AJAX request for read status successful:', response);
              },
              error: function(xhr, status, error) {
                  console.error('AJAX request error:', error);
              }
          });
      });
  </script>

<% end %>
<div class="box">
  <%= render @post %>
  <br><strong> Image :</strong> <br>
  <% if (@post.image.attached?) %>
    <%=image_tag @post.image %>
  <%else %>
    <%= "No Image" %>
  <%end %><br>

   <%= render 'ratings/rating',star_counts: @star_counts %>


</div>

<div>
  <%if can?(:manage,@post) %>
    <%= link_to "Edit this post", edit_topic_post_path(@post.topic,@post) ,class: "link"  %> |
    <br>
    <%= button_to "Destroy this post",  topic_post_path(@post.topic, @post), method: :delete ,class: "button"%>

<% end %>
  <%#= link_to "Edit this post", edit_topic_post_path(@post.topic,@post) ,class: "link"  %> |
  <%= link_to "Back to posts",topic_posts_path ,class: "link"%><br><br>

  <%#= button_to "Destroy this post",  topic_post_path(@post.topic, @post), method: :delete ,class: "button"%>
</div>
<div>

  <%= render "ratings/form",rating: @rating %>
  <%#= link_to "New Ratings", new_topic_post_rating_path(@post.topic,@post) %>
</div>